package ua.lviv.navpil.generics_are_hard.bridge_methods;

public class ComparablePerson implements Comparable<ComparablePerson> {

    @Override
    public int compareTo(ComparablePerson o) {
        return 0;
    }

    /*
    This won't compile, even though it looks like the signature is different from the compareTo(ComparablePerson)
    please see https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html for more information

    For those, too lazy to read: the method compareTo(Object) is autogenerated by Java, that's why we can't add
    it ourselves.
    */
//    public int compareTo(Object o) {return 0;}


    /*
    And even though the 'compareTo(Object)' method is generated behind the scenes, it is not actually available,
    so this code does not compile as well:
     */
//    public static void main(String[] args) {
//        new ComparablePerson().compareTo(new Object());
//    }
}

/*
For those interested, this class compiles to the following
(note the compareTo(Object) which as auto-generated)
----------------------------------------------------
Compiled from "ComparablePerson.java"
public class ua.lviv.navpil.generics_are_hard.bridge_methods.ComparablePerson implements java.lang.Comparable<ua.lviv.navpil.generics_are_hard.bridge_methods.ComparablePerson> {
  public ua.lviv.navpil.generics_are_hard.bridge_methods.ComparablePerson();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  public int compareTo(ua.lviv.navpil.generics_are_hard.bridge_methods.ComparablePerson);
    Code:
       0: iconst_0
       1: ireturn

  public int compareTo(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: checkcast     #2                  // class ua/lviv/navpil/generics_are_hard/bridge_methods/ComparablePerson
       5: invokevirtual #3                  // Method compareTo:(Lua/lviv/navpil/generics_are_hard/bridge_methods/ComparablePerson;)I
       8: ireturn
}

 */


